site_name: Project Thalassa
site_description: A bioinformatics data analysis platform for SRS risk assessment
site_url: https://ia-pierocv.github.io/Project_Thalassa
repo_url: https://github.com/IA-PieroCV/Project_Thalassa
repo_name: IA-PieroCV/Project_Thalassa

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for light mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Configuration: getting-started/configuration.md
  - User Guide:
    - API Overview: user-guide/api-overview.md
    - File Upload: user-guide/file-upload.md
    - Risk Assessment: user-guide/risk-assessment.md
  - API Reference:
    - Overview: api/overview.md
    - Endpoints: api/endpoints.md
  - Development:
    - Contributing: development/contributing.md
    - Testing: development/testing.md
    - Docker: development/docker.md
  - Changelog: ../CHANGELOG.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_bases: true
            show_inheritance_diagram: true
            members_order: source

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables

extra:
  version:
    provider: mike
